import json
import urllib.request
import os

API_BASE = "http://127.0.0.1:8000"
MOCK_FILE_PATH = os.path.join("trace-frontend", "src", "lib", "mockData.ts")

def fetch_json(url):
    try:
        with urllib.request.urlopen(url) as response:
            return json.loads(response.read().decode('utf-8'))
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return None

def main():
    print("Fetching cases...")
    cases = fetch_json(f"{API_BASE}/cases")
    if not cases:
        print("Failed to fetch cases. Is the backend running on http://localhost:8000?")
        return

    suspects_by_case = {}
    network_by_case = {}
    events_by_case = {}
    shared_contacts_by_case = {}
    suspect_profiles = {}
    movement_by_suspect = {}
    heatmap_by_suspect = {}

    for c in cases:
        case_id = c["id"]
        print(f"Processing case: {c['name']} ({case_id})")

        # Suspects
        suspects = fetch_json(f"{API_BASE}/cases/{case_id}/suspects")
        suspects_by_case[case_id] = suspects or []

        # Network
        network = fetch_json(f"{API_BASE}/cases/{case_id}/network")
        network_by_case[case_id] = network or {"nodes": [], "edges": []}

        # Events
        events = fetch_json(f"{API_BASE}/cases/{case_id}/events")
        events_by_case[case_id] = events or []

        # Shared Contacts
        shared = fetch_json(f"{API_BASE}/cases/{case_id}/shared-contacts")
        shared_contacts_by_case[case_id] = shared or []

        if suspects:
            for s in suspects:
                suspect_id = s["id"]
                print(f"  Fetching data for suspect: {s['label']} ({suspect_id})")

                # Profile
                profile = fetch_json(f"{API_BASE}/suspects/{suspect_id}/profile")
                suspect_profiles[suspect_id] = profile

                # Movement
                movement = fetch_json(f"{API_BASE}/suspects/{suspect_id}/movement")
                movement_by_suspect[suspect_id] = movement or []

                # Heatmap
                heatmap = fetch_json(f"{API_BASE}/suspects/{suspect_id}/call_heatmap")
                heatmap_by_suspect[suspect_id] = heatmap or []

    # Global Handlers
    print("Fetching global handlers...")
    global_handlers = fetch_json(f"{API_BASE}/global/handler-numbers") or []

    # Write to TypeScript file
    print(f"Writing to {MOCK_FILE_PATH}...")
    with open(MOCK_FILE_PATH, "w", encoding="utf-8") as f:
        f.write("/* eslint-disable */\n")
        f.write("// This file was automatically generated by dump_api_data.py\n\n")
        f.write(f"export const mockCases = {json.dumps(cases, indent=2)};\n\n")
        f.write(f"export const mockSuspectsByCase: Record<string, any[]> = {json.dumps(suspects_by_case, indent=2)};\n\n")
        f.write(f"export const mockNetworkByCase: Record<string, any> = {json.dumps(network_by_case, indent=2)};\n\n")
        f.write(f"export const mockEventsByCase: Record<string, any[]> = {json.dumps(events_by_case, indent=2)};\n\n")
        f.write(f"export const mockSharedContactsByCase: Record<string, any[]> = {json.dumps(shared_contacts_by_case, indent=2)};\n\n")
        f.write(f"export const mockSuspectProfiles: Record<string, any> = {json.dumps(suspect_profiles, indent=2)};\n\n")
        f.write(f"export const mockMovementBySuspect: Record<string, any[]> = {json.dumps(movement_by_suspect, indent=2)};\n\n")
        f.write(f"export const mockHeatmapBySuspect: Record<string, any[]> = {json.dumps(heatmap_by_suspect, indent=2)};\n\n")
        f.write(f"export const mockGlobalHandlers = {json.dumps(global_handlers, indent=2)};\n")

    print("Done!")

if __name__ == "__main__":
    main()
